apiVersion: apps/v1
kind: Deployment
metadata:
  name: inner-odd-checker-deployment
spec:
  selector:
    matchLabels:
      app: inner-odd-checker
  template:
    metadata:
      labels:
        app: inner-odd-checker
    spec:
      containers:
      - name: inner-odd-checker
        image: dsphoenix/inner-odd-checker:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7788
---
apiVersion: v1
kind: Service
metadata:
  name: inner-odd-checker-service
spec:
  selector:
    app: inner-odd-checker
  ports:
  - protocol: TCP
    port: 7788
    targetPort: 7788
